workspace: false

stages:
  - Install
  - Test
  - build
  - test
  - deploy

jobs:
  - name: Composer Install
    stage: Install
    image: sunasteriskrnd/php-workspace:7.4
    script:
    - composer install -d api
    cache:
    - key: vendor_$CI_BRANCH
      paths:
      - api/vendor
    - name: PHPUnit
      stage: Test
      image: sunasteriskrnd/php-workspace:7.4
      environment:
      - APP_ENV=testing
      script:
      - docker-php-ext-disable xdebug
      - cp .env.example .env.testing
      - php artisan key:generate
      - php artisan migrate
      - composer coverage
      coverage:
        type: clover
        path: api/coverage.xml
      artifacts:
        paths:
        - api/coverage
        expires_in: 3 days
    
  - name: Job1
    stage: build
    image: node:12-alpine
    allow_failure: true
    services:
      - redis:alpine
    before_script:
      - echo before_script
    script:
      - ls -la
      - echo "Build title should take only subject from commit message"
    after_script:
      - echo "Build title should take only subject from commit message"
    artifacts:
      paths:
      - app/Http
      expires_in: 3 days
    release:
      environment: test
      url: https://htt.com
  
  - name: Job33
    stage: build
    image: node:12-alpine
    allow_failure: false
    services:
      - redis:alpine
    before_script:
      - echo before_script
    script:
      - ls -la
      - echo "Build title should take only subject from commit message"
    after_script:
      - echo "Build title should take only subject from commit message"
    artifacts:
      paths:
      - app/Http
      expires_in: 3 days
    release:
      environment: test
      url: https://htt.com

  - name: Job 2
    stage: test
    image: node:12-alpine
    allow_failure: true
    script:
      - sleep 5
      - exit 1
      
  - name: Job 3
    stage: test
    image: node:12-alpine
    release:
      environment: production
      url: https://htt22.com
    script:
      - sleep 5
      - echo done
  - name: Job 4
    stage: deploy
    image: node:12-alpine
    release:
      environment: production
      url: https://htt.com
    script:
      - sleep 5
      - echo done
  - name: Job 5
    stage: deploy
    image: node:12-alpine
    release:
      environment: production
      url: https://htt.com
    script:
      - sleep 5
      - echo done
