workspace: true

stages:
  - build
  - test

jobs:
  build:
    stage: build
    image: node:12-alpine
    services:
      - redis:alpine
    before_script:
      - echo before_script
    script:
      - echo "Build title should take only subject from commit message"
    after_script:
      - echo "Build title should take only subject from commit message"

  test:
    stage: test
    image: alpine
    script:
      - echo "Build title should take only subject from commit message"
    except:
      branches:
        - develop
  test2:
    stage: test
    image: alpine
    script:
      - sleep 2 Build title should take only subject from commit message
      - echo ha
    except:
      branches:
        - master
  test3:
    stage: test
    image: alpine
    script:
      - sleep 2
      - echo ha
    except:
      branches:
        - develop
