executor: kubernetes
default:
  workspace: shared

stages:
- Test First
- Install
- Build
- Nothing
- Test

jobs:
- name: Test Result
  stage: Test First
  script:
    - echo ok333333333
    - echo "Cache $CI_BUILD_NUMBER\n" >> cache
    - cat cache
    - sleep 10
  image: alpine
  cache:
    - key:
        files:
        - .sun-ci.yml
      paths:
        - cache
  test_result:
    type: junit
    path: junit.xml
  coverage:
    type: clover
    path: coverage/coverage.xml
  artifacts:
    name: ar
    paths:
    - coverage
    expires_in: 3 days
- name: Test Result 2
  stage: Test First
  script:
    - echo ok
    - echo "Cache $CI_BUILD_NUMBER\n" >> cache
    - cat cache
    - sleep 10
  image: alpine
  cache:
    - key:
        files:
        - .sun-ci.yml
      paths:
        - cache
  test_result:
    type: junit
    path: junit.xml
  coverage:
    type: clover
    path: coverage/coverage.xml
  artifacts:
    name: ar
    paths:
    - coverage
    expires_in: 3 days
- name: Test Result 3
  stage: Test First
  script:
    - echo ok
    - echo "Cache $CI_BUILD_NUMBER\n" >> cache
    - cat cache
    - sleep 10
  image: alpine
  cache:
    - key:
        files:
        - .sun-ci.yml
      paths:
        - cache
  test_result:
    type: junit
    path: junit.xml
  coverage:
    type: clover
    path: coverage/coverage.xml
  artifacts:
    name: ar
    paths:
    - coverage
    expires_in: 3 days
- name: Docker dind
  stage: Test
  environment:
    DOCKER_HOST: tcp://docker:2375
  services:
    - redis
    - image: docker:20.10.17-dind
      environment:
        DOCKER_HOST: tcp://docker:2375
  script:
    - docker info
    - echo ok
    - echo "Cache $CI_BUILD_NUMBER\n" >> cache
    - cat cache
    
  image: docker:20.10.17
  
- name: Docker dind 2
  stage: Test
  environment:
    DOCKER_HOST: tcp://docker:2375
  services:
    - redis
    - image: docker:20.10.17-dind
      environment:
        DOCKER_HOST: tcp://docker:2375
  script:
    - docker info
    - echo ok
    - echo "Cache $CI_BUILD_NUMBER\n" >> cache
    - cat cache
    
  image: docker:20.10.17

