.skip-deploy: &skip-deploy
  messages:
  - '[ci skip deploy]'

stages:
- Test1
- Install
- Build
- Nothing22
- Test

jobs:
- name: Test Result
  stage: Test1
  script:
    - echo ok
    - echo "Cache $CI_BUILD_NUMBER\n" >> cache
    - cat cache
    - sleep 60
  image: alpine
  cache:
    - key:
        files:
        - .sun-ci.yml
      paths:
        - cache
  test_result:
    type: junit
    path: junit.xml
  coverage:
    type: clover
    path: coverage/coverage.xml
  artifacts:
    name: ar
    paths:
    - coverage
    expires_in: 3 days
