name: Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:20.10.17-dind
        env:
          DOCKER_HOST: "tcp://docker:2375"
          DOCKER_DRIVER: "overlay2"
          DOCKER_TLS_CERTDIR: ""

    steps:
      - name: Check docker service
        run: docker info
      - name: Check docker pull
        run: docker pull grafana/k6
