name: Node.js CI

on:
  pull_request:
    branches: [ "master" ]

jobs:
  Yarn-Install:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v2
      id: yarn-cache
      with:
        path: |
          **/node_modules
          **/.eslintcache
          ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: Yarn CLI
      # You may pin to the exact commit or the version.
      # uses: CultureHQ/actions-yarn@661c6f3a66041c2432bcfb78096b9207304614c8
      uses: CultureHQ/actions-yarn@v1.0.1
    - run: ls -la
    - run: yarn
    - run: echo "Yarn done"

