name: Node.js CI

on:
  pull_request:
    branches: [ "master" ]

jobs:
  Yarn-Install:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Yarn CLI
      # You may pin to the exact commit or the version.
      # uses: CultureHQ/actions-yarn@661c6f3a66041c2432bcfb78096b9207304614c8
      uses: CultureHQ/actions-yarn@v1.0.1
    - run: yarn
    - run: echo "Yarn done"
    - name: Cache node modules
      id: cache-node-modules
      uses: actions/cache@v3
      env:
        cache-name: cache-node-modules
      with:
        path: node_modules
        key: cache-node-modules
